[package]
name = "nikonova"
version = "0.1.0"
entrypoint = "src/lib.typ"

authors = ["Nile Jocson <atraphaxia@gmail.com>"]
license = "MPL-2.0"
repository = "https://github.com/atraphaxia/nikonova"
description = "For Math exercises, with a unique dark theme."
categories = ["fun", "report"]



[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
